/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BOOK4U;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author alumnat
 */
public class NewBookPage extends javax.swing.JPanel {

    boolean selected = false;

    public NewBookPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Barcelona = new javax.swing.JLabel();
        Madrid = new javax.swing.JLabel();
        Sevilla = new javax.swing.JLabel();
        Coruña = new javax.swing.JLabel();
        Zaragoza = new javax.swing.JLabel();
        Valencia = new javax.swing.JLabel();
        Valladolid = new javax.swing.JLabel();
        Asturias = new javax.swing.JLabel();
        Murcia = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        Resultado1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(25, 25));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Credits:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 980, 420, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PROFILE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, 50));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BOOKING HISTORY");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 400, 50));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel6.setText("NEW BOOKING");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 310, 50));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BOOKING DETAILS");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 380, 50));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SHOP");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, 120, 50));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flecha.png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 70, 80));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sidebar.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1080));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu (1).png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 70));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut_hover_big.png"))); // NOI18N
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut_hover.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 20, 60, 70));

        Barcelona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 410, -1, 100));

        Madrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, -1, 100));

        Sevilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Sevilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 680, -1, 100));

        Coruña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Coruña, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, -1, 100));

        Zaragoza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Zaragoza, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 410, -1, 100));

        Valencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Valencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 550, -1, 100));

        Valladolid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Valladolid, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, -1, 100));

        Asturias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Asturias, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, -1, 100));

        Murcia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chincheta.png"))); // NOI18N
        add(Murcia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 640, -1, 100));

        Resultado.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Resultado.setForeground(new java.awt.Color(102, 102, 102));
        add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 390, 50));

        Resultado1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Resultado1.setForeground(new java.awt.Color(102, 102, 102));
        add(Resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 420, 50));

        jTextField4.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        jTextField4.setText("Search here");
        jTextField4.setBorder(null);
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 300, 50));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa_basic.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa_hover.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 60, 70));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mainpage.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Barcelona.setVisible(false);
        Madrid.setVisible(false);
        Sevilla.setVisible(false);
        Coruña.setVisible(false);
        Zaragoza.setVisible(false);
        Valencia.setVisible(false);
        Valladolid.setVisible(false);
        Asturias.setVisible(false);
        Murcia.setVisible(false);
        Resultado.setText("");
        Resultado1.setText("");
        String userInput = jTextField4.getText().toUpperCase();

        if (userInput.equals("BARCELONA")) {
            Barcelona.setVisible(true);
        } else if (userInput.equals("MADRID")) {
            Madrid.setVisible(true);
        } else if (userInput.equals("SEVILLA")) {
            Sevilla.setVisible(true);
        } else if (userInput.equals("CORUÑA")) {
            Coruña.setVisible(true);
        } else if (userInput.equals("ZARAGOZA")) {
            Zaragoza.setVisible(true);
        } else if (userInput.equals("VALENCIA")) {
            Valencia.setVisible(true);
        } else if (userInput.equals("VALLADOLID")) {
            Valladolid.setVisible(true);
        } else if (userInput.equals("ASTURIAS")) {
            Asturias.setVisible(true);
        } else if (userInput.equals("MURCIA")) {
            Murcia.setVisible(true);
        } else {
            Resultado.setText("There are not results ");
            Resultado1.setText("with the name '" + userInput + "'");
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Controlador.setUser(null);
        System.out.println(Controlador.getUser());
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PanelBase());
        marco.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jButton13.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jButton13.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed

    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new ProfilePage());
        marco.setVisible(true);
        setearPerfil();

    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new ShopPage());
        marco.setVisible(true);
         ShopPage.jLabel9.setText("Credits: " + Controlador.getUsuarioInside().coins);
    }//GEN-LAST:event_jLabel8MouseClicked
    public void setearPerfil() {
        ProfilePage.Carga.setVisible(false);
        ProfilePage.Negro.setVisible(false);
        ProfilePage.jLabel9.setText("Credits: " + Controlador.getUsuarioInside().coins);
        ProfilePage.jTextField4.setText("" + Controlador.getUsuarioInside().dni);
        ProfilePage.jTextField3.setText("" + Controlador.getUsuarioInside().name);
        ProfilePage.jTextField5.setText("" + Controlador.getUsuarioInside().surname);
        ProfilePage.jTextField6.setText("" + Controlador.getUsuarioInside().adress);
        ProfilePage.jTextField7.setText("" + Controlador.getUsuarioInside().email);
        Controlador.Setimage();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Asturias;
    public static javax.swing.JLabel Barcelona;
    public static javax.swing.JLabel Coruña;
    public static javax.swing.JLabel Madrid;
    public static javax.swing.JLabel Murcia;
    public static javax.swing.JLabel Resultado;
    public static javax.swing.JLabel Resultado1;
    public static javax.swing.JLabel Sevilla;
    public static javax.swing.JLabel Valencia;
    public static javax.swing.JLabel Valladolid;
    public static javax.swing.JLabel Zaragoza;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
