/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BOOK4U;

import static BOOK4U.NewBookPage.Barcelona1;
import com.raven.datechooser.SelectedDate;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

import javax.swing.SwingUtilities;

/**
 *
 * @author alumnat
 */
public class NewbookPageCalendar extends javax.swing.JPanel {

    boolean selected = false;
    public static Apartamento ap;
    

    public NewbookPageCalendar() {
        initComponents();
        jLabel9.setText("Credits: " + Controlador.getUsuarioInside().coins);
        jButton13.setVisible(false);
        jLabel9.setVisible(false);
        jLabel8.setVisible(false);
        jLabel7.setVisible(false);
        jLabel6.setVisible(false);
        jLabel10.setText(Controlador.getUsuarioInside().name);
        jLabel5.setVisible(false);
        jLabel4.setVisible(false);
        casa.setVisible(false);
        Barcelona3.setVisible(false);
        jTextArea8.setVisible(false);
        jButton15.setVisible(false);
        jButton16.setVisible(false);
        boton_paypal.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton16 = new javax.swing.JButton();
        jTextArea8 = new javax.swing.JTextArea();
        jButton15 = new javax.swing.JButton();
        Barcelona3 = new javax.swing.JLabel();
        boton_paypal = new javax.swing.JLabel();
        jTextArea9 = new javax.swing.JTextArea();
        jTextArea5 = new javax.swing.JTextArea();
        jButton13 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        casa = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Barcelona2 = new javax.swing.JLabel();
        Barcelona1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jTextArea4 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        dateChooser1 = new com.raven.datechooser.DateChooser();
        dateChooser2 = new com.raven.datechooser.DateChooser();
        jLabel10 = new javax.swing.JLabel();
        Base = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(25, 25));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/no-hay-entrada.png"))); // NOI18N
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setFocusPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, 80, 90));

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Are you sure you want to rent this apartment?");
        jTextArea8.setToolTipText("");
        jTextArea8.setBorder(null);
        add(jTextArea8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 760, 60));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/controlar.png"))); // NOI18N
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 720, 70, 90));

        Barcelona3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alerta.png"))); // NOI18N
        add(Barcelona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 140, 2010, 1080));

        boton_paypal.setForeground(new java.awt.Color(102, 102, 102));
        boton_paypal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/negro.png"))); // NOI18N
        add(boton_paypal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1080));

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(255, 0, 0));
        jTextArea9.setRows(5);
        jTextArea9.setToolTipText("");
        jTextArea9.setBorder(null);
        add(jTextArea9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 960, 50));

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(255, 0, 0));
        jTextArea5.setRows(5);
        jTextArea5.setToolTipText("");
        jTextArea5.setBorder(null);
        add(jTextArea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 800, 470, 40));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flecha.png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 70, 80));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Credits:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 980, 420, 50));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SHOP");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, 120, 50));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BOOKING DETAILS");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 380, 50));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel6.setText("NEW BOOKING");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 310, 50));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BOOKING HISTORY");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 400, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PROFILE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, 50));

        casa.setForeground(new java.awt.Color(102, 102, 102));
        casa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sidebar.png"))); // NOI18N
        add(casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1080));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu (1).png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 60));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buy.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buy_hover.png"))); // NOI18N
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Buy_hover.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 860, 460, 90));

        Barcelona2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Marco.png"))); // NOI18N
        add(Barcelona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 500, 370));

        Barcelona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/casa_base.png"))); // NOI18N
        add(Barcelona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 400, 260));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut_hover_big.png"))); // NOI18N
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut_hover.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 20, 60, 70));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Fecha de Salida");
        jTextArea4.setToolTipText("");
        jTextArea4.setBorder(null);
        add(jTextArea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 510, 260, 40));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Fecha de Entrada");
        jTextArea3.setToolTipText("");
        jTextArea3.setBorder(null);
        add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 510, 290, 40));

        dateChooser1.setBackground(new java.awt.Color(204, 204, 204));
        dateChooser1.setForeground(new java.awt.Color(129, 204, 93));
        add(dateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 570, -1, -1));

        dateChooser2.setBackground(new java.awt.Color(204, 204, 204));
        dateChooser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateChooser2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dateChooser2MousePressed(evt);
            }
        });
        add(dateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 570, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 30, 310, 50));

        Base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NewBookingCalendar.png"))); // NOI18N
        add(Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jTextArea5.setText("");
        Barcelona3.setVisible(true);
        jTextArea8.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        boton_paypal.setVisible(true);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jButton13.setVisible(false);
        casa.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new ShopPage());
        marco.setVisible(true);
        ShopPage.jLabel9.setText("Credits: " + Controlador.getUsuarioInside().coins);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed

    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new ProfilePage());
        marco.setVisible(true);

    }//GEN-LAST:event_jLabel4MousePressed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jButton13.setVisible(true);
        casa.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new UserHistory());
        marco.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Controlador.setUser(null);
        System.out.println(Controlador.getUser());
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PanelBase());
        marco.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void dateChooser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateChooser2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooser2MouseClicked

    private void dateChooser2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateChooser2MousePressed

    }//GEN-LAST:event_dateChooser2MousePressed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       LocalDate fecha2 = null;
    LocalDate fecha1 = null;
    SelectedDate d = dateChooser1.getSelectedDate();
    String ent = String.format("%02d-%02d-%d", d.getDay(), d.getMonth(), d.getYear());

    SelectedDate d2 = dateChooser2.getSelectedDate();
    String sal = String.format("%02d-%02d-%d", d2.getDay(), d2.getMonth(), d2.getYear());

    try {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        fecha1 = LocalDate.parse(ent, formatter);
        fecha2 = LocalDate.parse(sal, formatter);
       

        if (fecha1.isBefore(fecha2) || fecha1.isEqual(fecha2)) {
            // Calcular la diferencia de días
            Period period = Period.between(fecha1, fecha2);
            int diasDiferencia = period.getDays();

            int pric2 = diasDiferencia * ap.getPrice();

            System.out.println(diasDiferencia);
            //String strNumero = Integer.toString(pric);
            BD.insertBooking(Controlador.con, ent, sal, ap.getId(), pric2, ap.getPlace());
        } else {
            jTextArea5.setText("Las fechas no son correctas");
        }
    } catch (DateTimeParseException ex) {
        Logger.getLogger(NewbookPageCalendar.class.getName()).log(Level.SEVERE, null, ex);
        jTextArea5.setText("Error al analizar las fechas");
    }

    Barcelona3.setVisible(false);
    jTextArea8.setVisible(false);
    jButton15.setVisible(false);
    jButton16.setVisible(false);
    boton_paypal.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Barcelona3.setVisible(false);
        jTextArea8.setVisible(false);
        jButton15.setVisible(false);
        jButton16.setVisible(false);
        boton_paypal.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed
    public void imagenes(Blob imagen) {
        Blob blob = imagen;
        byte[] imagenBytes = null;
        try {
            imagenBytes = blob.getBytes(1, (int) blob.length());
        } catch (SQLException e) {
            e.printStackTrace();
        }
        ImageIcon icono = new ImageIcon(imagenBytes);
        Barcelona1.setIcon(icono);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Barcelona1;
    public static javax.swing.JLabel Barcelona2;
    public static javax.swing.JLabel Barcelona3;
    private javax.swing.JLabel Base;
    public static javax.swing.JLabel boton_paypal;
    public static javax.swing.JLabel casa;
    private com.raven.datechooser.DateChooser dateChooser1;
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JFrame jFrame1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    public static javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea8;
    public static javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
