/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BOOK4U;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author alumnat
 */
public class ProfilePage extends javax.swing.JPanel {

    boolean selected = false;
    byte[] imageData = null;

    public ProfilePage() {
        initComponents();
        Carga.setVisible(false);
        Negro.setVisible(false);
       jLabel9.setText("Credits: " + Controlador.getUsuarioInside().coins);
        jTextField4.setText("" + Controlador.getUsuarioInside().dni);
        jTextField3.setText("" + Controlador.getUsuarioInside().name);
        jTextField5.setText("" + Controlador.getUsuarioInside().surname);
        jTextField6.setText("" + Controlador.getUsuarioInside().adress);
        jTextField7.setText("" + Controlador.getUsuarioInside().email);
        jLabel16.setText(Controlador.getUsuarioInside().name);
        Controlador.Setimage();
        BD.obtenerApartamentos(Controlador.con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Lapiz_User6 = new javax.swing.JLabel();
        Lapiz_User6.setVisible(false);
        Lapiz_User7 = new javax.swing.JLabel();
        Lapiz_User7.setVisible(false);
        Lapiz_User8 = new javax.swing.JLabel();
        Lapiz_User8.setVisible(false);
        Lapiz_User9 = new javax.swing.JLabel();
        Lapiz_User9.setVisible(false);
        Lapiz_User10 = new javax.swing.JLabel();
        Lapiz_User10.setVisible(false);
        Lapiz_User1 = new javax.swing.JLabel();
        Lapiz_User2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Lapiz_User3 = new javax.swing.JLabel();
        Lapiz_User4 = new javax.swing.JLabel();
        Lapiz_User5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lapiz_User = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Carga = new javax.swing.JLabel();
        Negro = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(25, 25));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lapiz_User6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        Lapiz_User6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User6MousePressed(evt);
            }
        });
        add(Lapiz_User6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 670, -1, 30));

        Lapiz_User7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        Lapiz_User7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User7MousePressed(evt);
            }
        });
        add(Lapiz_User7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 590, -1, 30));

        Lapiz_User8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        Lapiz_User8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User8MousePressed(evt);
            }
        });
        add(Lapiz_User8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 500, -1, 30));

        Lapiz_User9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        Lapiz_User9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Lapiz_User9MouseMoved(evt);
            }
        });
        Lapiz_User9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User9MousePressed(evt);
            }
        });
        add(Lapiz_User9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 410, -1, 30));

        Lapiz_User10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        Lapiz_User10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User10MousePressed(evt);
            }
        });
        add(Lapiz_User10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 760, -1, 30));

        Lapiz_User1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png"))); // NOI18N
        Lapiz_User1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User1MousePressed(evt);
            }
        });
        add(Lapiz_User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 750, 40, 50));

        Lapiz_User2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png"))); // NOI18N
        Lapiz_User2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User2MousePressed(evt);
            }
        });
        add(Lapiz_User2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 660, 40, 50));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setFocusable(false);
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, 500, 50));

        Lapiz_User3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png"))); // NOI18N
        Lapiz_User3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User3MousePressed(evt);
            }
        });
        add(Lapiz_User3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 580, 40, 50));

        Lapiz_User4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png"))); // NOI18N
        Lapiz_User4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User4MousePressed(evt);
            }
        });
        add(Lapiz_User4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 490, 40, 50));

        Lapiz_User5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png"))); // NOI18N
        Lapiz_User5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_User5MousePressed(evt);
            }
        });
        add(Lapiz_User5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 400, 40, 50));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(102, 102, 102));
        jTextField7.setBorder(null);
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 758, 310, 40));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jTextField6.setBorder(null);
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, 310, 40));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.setBorder(null);
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 670, 310, 40));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        jTextField4.setBorder(null);
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 408, 320, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setBorder(null);
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 500, 320, 40));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel13.setText("Dni");
        jLabel13.setFocusable(false);
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 80, 50));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 30, 310, 50));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel14.setText("Adress");
        jLabel14.setFocusable(false);
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 150, 50));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel10.setText("Name");
        jLabel10.setFocusable(false);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 130, 50));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel11.setText("Surname");
        jLabel11.setFocusable(false);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 660, 190, 50));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel12.setText("Email");
        jLabel12.setFocusable(false);
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 750, 130, 50));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Credits:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 980, 400, 50));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SHOP");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, 120, 50));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BOOKING DETAILS");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 380, 50));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NEW BOOKING");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 310, 50));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BOOKING HISTORY");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 400, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel4.setText("PROFILE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, 50));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flecha.png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 70, 80));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sidebar.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1080));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 310, 250));

        Lapiz_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png"))); // NOI18N
        Lapiz_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lapiz_UserMousePressed(evt);
            }
        });
        add(Lapiz_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 690, 40, 50));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu (1).png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 60));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut_hover_big.png"))); // NOI18N
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logOut_hover.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 20, 60, 70));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProfilePage_cuadro.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1080));

        Carga.setForeground(new java.awt.Color(102, 102, 102));
        Carga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/03-42-15-221_512.gif"))); // NOI18N
        Carga.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                CargaComponentHidden(evt);
            }
        });
        add(Carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 210, 240));

        Negro.setForeground(new java.awt.Color(102, 102, 102));
        Negro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/negro.png"))); // NOI18N
        add(Negro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Controlador.setUser(null);
        System.out.println(Controlador.getUser());
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new PanelBase());
        marco.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void Lapiz_UserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_UserMousePressed

        JFileChooser chooser = new JFileChooser();

        chooser.showOpenDialog(jLabel1);
        File imageFile = chooser.getSelectedFile();
        try {
            FileInputStream fis = new FileInputStream(imageFile);
            imageData = new byte[(int) imageFile.length()];
            fis.read(imageData);
            fis.close();
            Carga.setVisible(true);
            Negro.setVisible(true);
            BD.Imagencasa(Controlador.con, imageData, 18);
            //Controlador.setUsuarioInside(BD.Imagen(Controlador.con, imageData));

            /*            BD.Imagen(Controlador.con, imageData);
           
            Controlador.Setimage();*/
            //carga10();
            // Resto del código para almacenar la imagen en la base de datos
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println(imageData.toString());

    }//GEN-LAST:event_Lapiz_UserMousePressed

    private void CargaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CargaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_CargaComponentHidden

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jButton13.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jButton13.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked

    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void Lapiz_User1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User1MousePressed

        if (jTextField7.isEditable() == false) {
            jTextField7.setEditable(true);
             Lapiz_User10.setVisible(true);
             Lapiz_User1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz_rojo.png")));
        } else {
            jTextField7.setEditable(false);
             Lapiz_User10.setVisible(false);
             Lapiz_User1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
        }

    }//GEN-LAST:event_Lapiz_User1MousePressed

    private void Lapiz_User2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User2MousePressed
        if (jTextField5.isEditable() == false) {
            jTextField5.setEditable(true);
             Lapiz_User6.setVisible(true);
             Lapiz_User2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz_rojo.png")));
        } else {
            jTextField5.setEditable(false);
             Lapiz_User6.setVisible(false);
             Lapiz_User2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
        }
    }//GEN-LAST:event_Lapiz_User2MousePressed

    private void Lapiz_User3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User3MousePressed
        if (jTextField6.isEditable() == false) {
            jTextField6.setEditable(true);
             Lapiz_User7.setVisible(true);
             Lapiz_User3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz_rojo.png")));
        } else {
            jTextField6.setEditable(false);
             Lapiz_User7.setVisible(false);
             Lapiz_User3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
        }
    }//GEN-LAST:event_Lapiz_User3MousePressed

    private void Lapiz_User4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User4MousePressed
        if (jTextField3.isEditable() == false) {
            jTextField3.setEditable(true);
            Lapiz_User8.setVisible(true);
            Lapiz_User4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz_rojo.png")));
        } else {
            jTextField3.setEditable(false);
            Lapiz_User8.setVisible(false);
            Lapiz_User4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
        }
    }//GEN-LAST:event_Lapiz_User4MousePressed

    private void Lapiz_User5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User5MousePressed
        if (jTextField4.isEditable() == false) {
            jTextField4.setEditable(true);
            Lapiz_User9.setVisible(true);
            Lapiz_User5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz_rojo.png")));
        } else {
            jTextField4.setEditable(false);
            Lapiz_User9.setVisible(false);
            Lapiz_User5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
        }
    }//GEN-LAST:event_Lapiz_User5MousePressed

    private void Lapiz_User6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User6MousePressed
         System.out.println(jTextField3.getText()); 
        Controlador.setUsuarioInside(BD.update(Controlador.con, jTextField5.getText(),"surname"));
     
            jTextField5.setEditable(false);
            Lapiz_User6.setVisible(false);
            Lapiz_User2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
    }//GEN-LAST:event_Lapiz_User6MousePressed

    private void Lapiz_User7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User7MousePressed
       System.out.println(jTextField3.getText()); 
        Controlador.setUsuarioInside(BD.update(Controlador.con, jTextField6.getText(),"adress"));
     
            jTextField6.setEditable(false);
            Lapiz_User7.setVisible(false);
            Lapiz_User3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
    }//GEN-LAST:event_Lapiz_User7MousePressed

    private void Lapiz_User8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User8MousePressed
        System.out.println(jTextField3.getText()); 
        Controlador.setUsuarioInside(BD.update(Controlador.con, jTextField3.getText(),"name"));
     
            jTextField3.setEditable(false);
            Lapiz_User8.setVisible(false);
            Lapiz_User4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
    }//GEN-LAST:event_Lapiz_User8MousePressed

    private void Lapiz_User9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User9MousePressed
       
        if (Controlador.esDNIValido(jTextField4.getText())) {
            System.out.println(jTextField4.getText()); 
        Controlador.setUsuarioInside(BD.dni(Controlador.con, jTextField4.getText()));
     
            jTextField4.setEditable(false);
            Lapiz_User9.setVisible(false);
            Lapiz_User5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
        } else {
            jLabel15.setText("El DNI no es válido.");
            jTextField4.setEditable(false);
            Lapiz_User9.setVisible(false);
            Lapiz_User5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
        }
//este
    }//GEN-LAST:event_Lapiz_User9MousePressed

    private void Lapiz_User10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User10MousePressed
        System.out.println(jTextField7.getText()); 
        Controlador.setUsuarioInside(BD.update(Controlador.con, jTextField7.getText(),"email"));
     
            jTextField7.setEditable(false);
            Lapiz_User10.setVisible(false);
            Lapiz_User1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lapiz.png")));
        
    }//GEN-LAST:event_Lapiz_User10MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new NewBookPage());
        marco.setVisible(true);
        NewBookPage.jLabel9.setText("Credits: " + Controlador.getUsuarioInside().coins);
        NewBookPage.Barcelona.setVisible(false);
        NewBookPage.Madrid.setVisible(false);
        NewBookPage.Sevilla.setVisible(false);
        NewBookPage.Coruña.setVisible(false);
        NewBookPage.Zaragoza.setVisible(false);
        NewBookPage.Valencia.setVisible(false);
        NewBookPage.Valladolid.setVisible(false);
        NewBookPage.Asturias.setVisible(false);
        NewBookPage.Murcia.setVisible(false);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new ShopPage());
        marco.setVisible(true);
        ShopPage.jLabel9.setText("Credits: " + Controlador.getUsuarioInside().coins);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
  JFrame marco = (JFrame) SwingUtilities.getWindowAncestor(this);
        marco.remove(this);
        marco.add(new UserHistory());
        marco.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void Lapiz_User9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lapiz_User9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Lapiz_User9MouseMoved

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MousePressed
    public void carga10() {

        int segundos = 5;
        BD.Imagen(Controlador.con, imageData);

        for (int i = segundos; i > 0; i--) {
            System.out.println("Quedan " + i + " segundos.");
            try {
                Thread.sleep(1000); // Pausa de 1 segundo
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

        Controlador.Setimage();
        Carga.setVisible(false);
        Negro.setVisible(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Carga;
    public static javax.swing.JLabel Lapiz_User;
    public static javax.swing.JLabel Lapiz_User1;
    public static javax.swing.JLabel Lapiz_User10;
    public static javax.swing.JLabel Lapiz_User2;
    public static javax.swing.JLabel Lapiz_User3;
    public static javax.swing.JLabel Lapiz_User4;
    public static javax.swing.JLabel Lapiz_User5;
    public static javax.swing.JLabel Lapiz_User6;
    public static javax.swing.JLabel Lapiz_User7;
    public static javax.swing.JLabel Lapiz_User8;
    public static javax.swing.JLabel Lapiz_User9;
    public static javax.swing.JLabel Negro;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    public static javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
